blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/furkankoykiran/speedapi_lib/discussions
    about: Ask questions and discuss ideas here
  - name: 📖 Documentation
    url: https://docs.tryspeed.com
    about: Speed API official documentation
